version: "3.8"
services:
    datascience-notebook:
        image: jupyter/datascience-notebook
        ports:
          - 8888:8888
        volumes:
          - ./analytics/notebooks:/home/jovyan/work/
    db:
      build: ./database/